### ISSUE TITLE
grep 3.11 - Update tool

### ISSUE THREAD

**Issue by bovirus** [mbuilov/grep-windows#7]
@mbuilov 

Could you please update tool using latest source 3.11?

Thanks.

**Comment by bovirus** [comment]
@mbuilov 

Could you pelase update your tool with latest source?

**Comment by bovirus** [comment]
@mbuilov 

No answer? Thanks.

**Comment by DiMarco1976** [comment]
Would also be happy of a patched Win64-version of 3.11.
The Git-for-Windows version still is 3.0 from 2017 and I use your patched 3.8 version.
Maybe you wait until the -r switch bug is fixed?
Thank you for patching.

**Comment by mbuilov** [comment]
> @mbuilov
> 
> Could you pelase update your tool with latest source?
> No answer? Thanks.

Unfortunately, I don't have much free time, even for reading emails.
Please don't take it personally if I don't respond for a long time.



> Maybe you wait until the -r switch bug is fixed?

I quite accidentally discovered that by setting the host type to mingw64 or mingw32 while the grep configuration, the emulation of the readdir() function in gnulib is enabled.

Therefore, now recursive file search is working, however, rather slowly compared to pcre2grep or grep-3.11 from Cygwin.

**Comment by rollingmoai** [comment]
I recommend checking out [ugrep](https://github.com/Genivia/ugrep). It works for Windows and is compatible with grep syntax.
