### ISSUE TITLE
FR: command line argument wildcard expansion

### ISSUE THREAD

**Issue by ian-abbott** [mbuilov/grep-windows#9]
The pre-built `grep` executables do not do any wildcard expansion (globbing) of the command line parameters. Quite often, I would like to grep for a pattern within a group of files specified by a wildcard, such as `*.c`, but the prebuilt binaries report `*.c` as an invalid argument. Strangely, the pre-built `pcre2grep` executables *do* support wildcard expansion of the command line parameters!

**Comment by mbuilov** [comment]
Yes, the same problem was with sed.exe - it is needed just to link wsetargv.obj to the grep.exe.

Done.
